dail8859/NotepadNext

.github/workflows/build.yml

Using all cpu cores decreases compilation time almost half of time. Sweet! I dunno why i didn't use it in first place.

Use all cpu cores for compilation

---

.github/workflows/build.yml

When switching between Qt5 and Qt6 it could lead to crashes or loss of settings due to this bug that was finally fixed.
> QTBUG-96916 Qt 6 breaks compatibility of QVariant streaming into QDataStream

Use Qt 6.2.4

---

deploy/linux/com.github.dail8859.NotepadNext.metainfo.xml
doc/Create Release.md

because otherwise it will report the wrong application version in Flathub and Flatpak:
despite having v0.5 installed

Reminder that metainfo file also needs to include new releases

---

src/NotepadNext/dialogs/MainWindow.cpp

Without this Patch:
```
Copy Full Path: 	E:\github\NotepadNext\src
Copy File Name: 	Version.pri
Copy File Directory: 	E:\github\NotepadNext\src\Version.pri
```
This PR:
```
Copy Full Path: 	E:\github\NotepadNext\src\Version.pri
Copy File Name: 	Version.pri
Copy File Directory:	E:\github\NotepadNext\src
```
Note:
- `editor->getFilePath()` ==> `fileInfo.canonicalFilePath()`
> Returns the canonical path _including the file name_
- `editor->getPath()` ==> `fileInfo.canonicalPath()`
> Returns the file's path canonical path (_excluding the file name_)

Fix "Copy Full Path" & "Copy File Directory"

---

deploy/linux/NotepadNext.desktop

This will fix the issue of NotepadNext not being listed in the "open with" dialogue when opening text files. 
Currently it is not listed at all unless it is manually selected.

add text/plain mime type to .desktop

---

deploy/linux/com.github.dail8859.NotepadNext.metainfo.xml

fixes developer name missing on the Flathub page:

fix developer name missing in metainfo

---

i18n/NotepadNext.zh_CN.ts
src/NotepadNext/dialogs/FindReplaceDialog.cpp
src/NotepadNext/dialogs/MainWindow.cpp
src/NotepadNext/docks/EditorInspectorDock.cpp
src/NotepadNext/docks/LanguageInspectorDock.cpp
src/NotepadNext/widgets/EditorInfoStatusBar.cpp

I open this PR for the issue #56
For translation, the hardcoded string literals need to be wrapped with tr(). This does not affect the current state of the program, if no translation files are present, the default English phrases are displayed.
Note that in some cases I replaced QStringLiteral with tr, but it shouldn't be a problem at all. (in the function *void EditorInspectorDock::updateEditorInfo(ScintillaNext *editor)* and in several places in *EditorInfoStatusBar.cpp* file)

Wrap string literals with tr() for translation

---

src/NotepadNext/EditorManager.cpp

Closes #111
The default font size on my Windows setup is 8, but that looks a bit small. 10 is much nicer. This uses the system default font size and increases it by 2. The rational being the text in the editor probably needs to be bigger than the rest of the UI (menu, labels, etc).

Adjust default font sized based on UI font size

---

i18n/NotepadNext.zh_CN.ts

Close #56
Most of the strings are already translated, but they need a second review.
I'll open the draft pr first to make it easier for people to review.
TODO:
Most of the text has already been translated.
For a few uncertain sentences, I have added `TODO` markers in the comments

[i18n/zh-cn] Chinese translation

---

src/NotepadNext.pro
src/NotepadNext/NotepadNextApplication.cpp
src/NotepadNext/NotepadNextApplication.h
src/i18n.pri

The translation of `Qt_base` for Simplified Chinese is not complete, so this patch does not actually copy any files.
You can test the `windeployqt` process by adding a new ts file to the i18n folder.
eg.: 
```sh
cd i18n/
cp NotepadNext.zh_CN.ts  NotepadNext.zh_TW.ts
cp NotepadNext.zh_CN.ts  NotepadNext.en.ts
```
After `jom package`, you may get `build\package\translations\qt_*.qm`

[i18n] load translations for Qt

---

installer/installer.nsi

I think a start menu shortcut, context menu, and an auto-updater are what users would want by default in an installation. This is especially important for Winget users, as it runs silently by default, and they would expect it to appear in the Start Menu right after installation.

Enable some NSIS Components by default

---

.github/workflows/post_release.yml
README.md

This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.
[Notepad Next](https://github.com/microsoft/winget-pkgs/tree/master/manifests/d/dail8859/NotepadNext) is already in Winget, and this workflow will be used to update it.
Before merging this:
1. Add a PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN` (or rename the secret name in the workflow).
2. Fork https://github.com/microsoft/winget-pkgs under @dail8859. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Sign the [Contributor License …

Add Winget Releaser workflow

---

src/NotepadNext/MacroStep.cpp

Scintilla for some reason defines the wParam and lParam sizes differently and on MacOS and Linux they are not compatible to a built in version that the QDataStream can handle.

Fix saving/loading Macros on non-Window systems

---

.github/dependabot.yml
.github/workflows/post_release.yml

Winget Releaser is now switching to version tags instead of the `latest` tag.
As mentioned in https://github.com/dail8859/NotepadNext/issues/208#issuecomment-1258827654, please install the [Pull](https://github.com/apps/pull) app on the winget-pkgs fork to ensure that it is always updated.

Update Winget Releaser workflow

---

src/NotepadNext/EditorHexViewerTableModel.cpp

In the Hex Viewer the char values bigger than 0x7f is interpreted as negative integer and is padded with leading 'FF' when displaying.
This commit cast the char value returned by scintilla to 'unsigned char' before formatting it to QString for displaying.

Fix displaying of non-ascii chars in Hex Viewer

---

src/NotepadNext/FileDialogHelpers.cpp
src/NotepadNext/FileDialogHelpers.h
src/NotepadNext/NotepadNext.pro
src/NotepadNext/dialogs/MainWindow.cpp

Several QFileDialog static methods had to be copied and slightly tweaked so that the QDir::Filters can be specified.
See https://github.com/dail8859/NotepadNext/discussions/255

Show hidden files on file dialogs for Linux

---

src/NotepadNext/DockedEditor.cpp
src/NotepadNext/EditorManager.cpp
src/NotepadNext/EditorManager.h
src/NotepadNext/NotepadNext.pro
src/NotepadNext/NotepadNextApplication.cpp
src/NotepadNext/NotepadNextApplication.h
src/NotepadNext/ScintillaNext.cpp
src/NotepadNext/ScintillaNext.h
src/NotepadNext/SessionManager.cpp
src/NotepadNext/SessionManager.h
src/NotepadNext/Settings.cpp
src/NotepadNext/Settings.h
src/NotepadNext/dialogs/MainWindow.cpp
src/NotepadNext/dialogs/MainWindow.h
src/NotepadNext/dialogs/PreferencesDialog.cpp
src/NotepadNext/dialogs/PreferencesDialog.ui
src/NotepadNext/docks/FileListDock.cpp

This is a first attempt at saving/loading a user's session between application restarts.
This feature is **not** enabled by default. This needs enabled through the preferences dialog.
~~This feature does **not** currently save temporary files (that will come later). This base functionality is needed before temporary files can be properly saved/loaded.~~
TODO:

Restore opened files between application restarts

---

src/NotepadNext/NotepadNextApplication.cpp

It should be a `QLocale::system`'s bug, when the Windows region is "English(United States)", the `QLocale::system` detects the region correctly. However when passing the locale object to `QTranslator::load`, it wrongly loads the zh_CN translation file.
Actually, it's a workaround by constructing a new `QLocale` object with a given name obtained from `QLocale::system`.
```
[     0.064] I: =============================
[     0.064] I: Notepad Next v0.6.1.0
[     0.064] I: Build Date/Time: May  6 2023 22:42:49
[     0.064] I: Qt: 6.5.0
[     0.064] I: OS: Windows 10 Version 22H2
[     0.064] I: Locale: zh_CN
[     0.064] I: CPU: x86_64
[     0.064] I: File Path: C:/dev/NotepadNext/build-NotepadNext-Desktop_Qt_6_5_0_MSVC2019_64bit-Debug/NotepadNext/NotepadNext.exe
[     0.064] I: Arguments: …
```

Fix English tranlation issue #370

---

src/scintilla/qt/ScintillaEditBase/ScintillaEditBase.cpp

Fix a crash issue on Mac: https://github.com/dail8859/NotepadNext/issues/194
`Scintilla::Internal::UTF32FromUTF8` throws an exception. 
`——` contains two characters `—`, so need to call `sqt->InsertCharacter` twice to insert the two characters, just like `ScintillaEditBase::inputMethodEvent`
Calling `sqt->InsertCharacter` twice to insert the two characters `—`.
With the fix, can enter `——` on Mac now.

Fix issue 194: Mac crash of ——

---

src/NotepadNext/docks/HexViewerDock.cpp

When opening Notepad Next on Mac, can always see this warning:
```
[     0.595] W: Populating font family aliases took 147 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost.
```
Changing hex view font family to "Courier New"

Fix hex view font family issue

---

src/NotepadNext/QRegexSearch.cpp

Fix issue  #374 No response when scrolling up and down.
Scintilla runs the regex search too slowly, so `while (editor->send(SCI_FINDTEXT, flags, (sptr_t)&ttf) != -1)` takes a long, then blocks the main thread.
Before the fix:
After the fix:

Fix issue #374 No response when scrolling up and down

---

src/NotepadNext/docks/SearchResultsDock.cpp

When a new search result is added, all the other search results will be collapsed, then always need to expand 2 times to check a previous search result.
Only collapse top levels when a new search result is added.

Collapse top level items when a new search result is added

---

src/NotepadNext/docks/SearchResultsDock.cpp
src/NotepadNext/docks/SearchResultsDock.h

Commit https://github.com/dail8859/NotepadNext/commit/940cc193ea730d0c54ec120ca353850726cfd1d2 optimized SearchResultsDock to make it resize the column to contents. However, it doesn't work well in this scenario that after a new short line is added in SearchResultsDock, the previous long line's column will be shortened.
Call "ui->treeWidget->resizeColumnToContents(1)" to resize the column when the searched item is expanded.

Fix bug SearchResultsDock doesn't resize column to contents

---

src/NotepadNext/docks/SearchResultsDock.ui

In the search results dock, when hovering over the last line of the search results, the horizontal scrollbar will show and overlap with the last line, so it's hard to click the last line of the search results.
Change the search results dock's vertical scroll mode from the default value QAbstractItemView::ScrollPerPixel to QAbstractItemView::ScrollPerItem.

Optimize search results dock scroll on Mac

---

.github/workflows/post_release.yml

Winget Releaser now supports non-Windows runners, and `ubuntu-latest` is generally faster.

Change Winget Releaser job to `ubuntu-latest`

---

i18n/NotepadNext_zh_CN.ts

-  `̶书签`̶ ̶ ̶>̶ ̶`̶标签`̶ ̶ ̶(̶N̶e̶e̶d̶ ̶t̶o̶ ̶o̶n̶ ̶t̶h̶e̶ ̶s̶a̶m̶e̶ ̶p̶a̶g̶e̶)̶
- T̶r̶a̶n̶s̶l̶a̶t̶e̶ ̶`̶O̶p̶e̶n̶`̶ ̶i̶n̶t̶o̶ ̶`̶打开` i̶n̶
https://github.com/dail8859/NotepadNext/blob/b0ec36c1f6d9672dce0a505c06bbcdc6bcaae4f9/i18n/NotepadNext_zh_CN.ts#L124-L125
Signed-off-by: yangyangdaji <1504305527@qq.com>

(I18N) Chinese Simplified Translation Update

---

deploy/macos/info.plist

Updated `CFBundleIdentifier` to follow the format used by some other OSS projects such as [OpenToonz](https://github.com/opentoonz/opentoonz): `io.github.opentoonz.OpenToonz`
Old: `~/Library/Saved Application State/com.yourcompany.NotepadNext.savedState` 
New: `~/Library/Saved Application State/io.github.dail8859.NotepadNext.savedState`

CFBundleIdentifier

---

src/NotepadNext/dialogs/FindReplaceDialog.ui
src/NotepadNext/dialogs/PreferencesDialog.ui

The [ Translation ] option is not in the correct location on form.
Before:
After:

Adapt the Preference dialog UI for MAC 

---

src/NotepadNext/dialogs/MainWindow.cpp
src/NotepadNext/dialogs/MainWindow.h

Closes #569. Adding a `[Shortcuts]` section in the ini file will override the default shortcuts. https://doc.qt.io/qt-6/qkeysequence.html#QKeySequence-1 is used to parse out the shortcut string. E.g.
```ini
[Shortcuts]
New=Ctrl+F1
```

Allow overriding shortcut keys

---

src/NotepadNext/QuickFindWidget.cpp
src/NotepadNext/QuickFindWidget.h
src/NotepadNext/QuickFindWidget.ui

This also overhauls the internals a bit and caches all the locations (since it highlights them anyways) and just uses that list to navigate. In theory the document shouldn't change while the QuickFindWidget is opened, meaning the cached search results will always be valid. Closes #546

Add match count to Quick Find

---

src/NotepadNext/ApplicationSettings.cpp
src/NotepadNext/ApplicationSettings.h
src/NotepadNext/dialogs/FindReplaceDialog.cpp
src/NotepadNext/dialogs/FindReplaceDialog.h
src/NotepadNext/dialogs/PreferencesDialog.cpp
src/NotepadNext/dialogs/PreferencesDialog.ui

Adds the option of having the search dialog center on the main window.

Issue 325 : Search Box Positioning

---

src/NotepadNext/dialogs/FindReplaceDialog.cpp

Fix for issue "Backward direction does not work in Find #628"

Add backward direction to Find dialog

---

src/Config.pri

Closes #580. See: https://stackoverflow.com/questions/78598141/first-stdmutexlock-crashes-in-application-built-with-latest-visual-studio

Attempt to fix Win10 crash

---

src/scintilla/include/ScintillaTypes.h
src/scintilla/qt/ScintillaEditBase/PlatQt.h
src/scintilla/qt/ScintillaEditBase/ScintillaEditBase.h

I had to add cstdin in 3 places to make it compile successfully with the upcoming gcc15, because cstdin is not automatically included anymore.  Reference: https://gcc.gnu.org/gcc-15/porting_to.html and https://sourceforge.net/p/scintilla/bugs/2458/
I am no expert, so I don't know what style guidelines are custom for the placement of those includes.  If necessary, I can adapt the commits. Let me know what you think, thanks
The corresponding bug report is #669

Include cstdin in scintilla for GCC15 compatibility

---

src/NotepadNext/dialogs/MainWindow.cpp

If there was a single temporary file this was getting treated as a brand new, unmodified editor which means the app was treating this as one that could be closed since it was not needed. Closes #674

Fix loss when having a single temporary file

---

src/NotepadNext/EditorManager.cpp
src/NotepadNext/EditorManager.h

Auto detect EOL mode

---

src/NotepadNext/ApplicationSettings.cpp
src/NotepadNext/ApplicationSettings.h
src/NotepadNext/EditorManager.cpp
src/NotepadNext/ScintillaNext.cpp
src/NotepadNext/ScintillaNext.h
src/NotepadNext/dialogs/PreferencesDialog.cpp
src/NotepadNext/dialogs/PreferencesDialog.ui

Add default end of line setting

---

src/NotepadNext/dialogs/FindReplaceDialog.cpp
src/NotepadNext/dialogs/FindReplaceDialog.h
src/NotepadNext/dialogs/FindReplaceDialog.ui

Make Find/Replace Dialog resize-able

---

i18n/NotepadNext_es_NI.ts

Here's my second pull request to the `master` branch, regarding the Nicaraguan Spanish translation with the following changes:
1. Fix some minor spelling mistakes I did during the translation process.
2. Translate some strings that had no Spanish translation.
3. Fix some Spanish translation strings so they can (kind of) make sense for Spanish speakers.

Update Spanish (Nicaragua, es_NI) translation.

---

i18n/NotepadNext_cs.ts
i18n/NotepadNext_es.ts
i18n/NotepadNext_pl.ts
i18n/NotepadNext_ru.ts
i18n/NotepadNext_sv.ts
i18n/NotepadNext_tr.ts
i18n/NotepadNext_uk.ts
src/NotepadNext/TranslationManager.cpp
src/NotepadNext/dialogs/PreferencesDialog.cpp
src/i18n.pri

For most cases translation files just need the language and not the country/territory as well. This better aligns to Qt and other Qt-based applications.

Rework translation file naming

---

src/NotepadNext/ActionUtils.h
src/NotepadNext/NotepadNext.pro
src/NotepadNext/dialogs/MainWindow.cpp
src/NotepadNext/dialogs/MainWindow.h
src/NotepadNext/dialogs/MainWindow.ui

Allow customized toolbar

---

src/NotepadNext/NotepadNext.pro
src/NotepadNext/SearchResultData.h
src/NotepadNext/SearchResultHighlighterDelegate.cpp
src/NotepadNext/SearchResultHighlighterDelegate.h
src/NotepadNext/docks/SearchResultsDock.cpp

Highlight search results

---

.gitignore
src/NotepadNext/dialogs/FindReplaceDialog.ui
src/NotepadNext/dialogs/MainWindow.cpp

This fixes issue #779 on Qt5 while retaining Qt6 compatibility. It now includes a separate block using the #if and #elif blocks to determine which block runs depending on Qt version. It also adds a Find All in Files button. Looks like most of what is needed to implement Find in Files is ready, so someone else can probably do the actual functionality, and therefore, I'll include this button in the Find and Replace dialog. The .gitignore is also updated to ignore cache files created by some popular C++ IDEs and all build folders (some people like me like to create numbered build folders to preserve older builds).

Fix Qt 5 compatibility and add Find All in Files button

---

src/NotepadNext/dialogs/MainWindow.cpp
src/NotepadNext/widgets/EditorInfoStatusBar.cpp
src/NotepadNext/widgets/EditorInfoStatusBar.h

Allow clicking on EOL label in status bar

---

src/NotepadNext/ApplicationSettings.cpp
src/NotepadNext/ApplicationSettings.h
src/NotepadNext/EditorManager.cpp
src/NotepadNext/dialogs/PreferencesDialog.cpp
src/NotepadNext/dialogs/PreferencesDialog.ui

Allow toggling visibility of line numbers

---

src/NotepadNext/ScintillaNext.cpp

This PR is a part of modification approved to implement in #825 issue thread. In this PR double clicking on search result caret is placed at the end of selection.
- In ScintillaNext goToRange function during selecting text the anchor and caret position are changed

Change caret position to range end and anchor to range start
