src/NotepadNext/dialogs/MainWindow.cpp, src/NotepadNext/dialogs/MainWindow.ui
This fixes the issue  **About needs to be the last entry in the Help menu #86**
=> Fix Help menu action order

.github/workflows/build.yml
=> Use older Linux to build AppImage

src/NotepadNext/LuaExtension.cpp, src/NotepadNext/LuaExtension.h, src/NotepadNext/NppImporter.cpp, src/NotepadNext/ScintillaNext.cpp, src/NotepadNext/decorators/BetterMultiSelection.cpp, src/NotepadNext/dialogs/MainWindow.cpp, src/NotepadNext/docks/LuaConsoleDock.cpp
Contains several fixes to reduce warnings  - also https://github.com/dail8859/NotepadNext/issues/99.
After this PR - I only have warnings about unused functions, or variables.
=> Reduce warnings

src/NotepadNext/NotepadNext.pro
=> Support PREFIX for Linux installation directory

doc/Translation.md, src/NotepadNext.pro
A translation process guide for #56 
This is the very first version of the guide. It might change as we start to implement the translation and find out the actual tricks about it.
I can start to work on it the next week.
=> Add Translation doc

src/NotepadNext/NotepadNextApplication.cpp, src/NotepadNext/NotepadNextApplication.h
=> Implement QFileOpenEvent for MacOS

src/NotepadNext/NotepadNextApplication.cpp
=> Specify the translation file path relative to the exe

src/scintilla/qt/ScintillaEditBase/ScintillaEditBase.cpp, src/scintilla/qt/ScintillaEditBase/ScintillaQt.cpp
=> Fix Scintilla's RectangularSelectionModifier for Qt

src/NotepadNext/LuaExtension.cpp, src/NotepadNext/ScintillaNext.h, src/NotepadNext/dialogs/FindReplaceDialog.cpp, src/NotepadNext/docks/LuaConsoleDock.cpp
Some unused functions, and arguments.
As I am using a C++17 switch, I am a little worried...
Is C++17 the version we are aiming for...?
=> Redeuce some warnings

src/NotepadNext/DockedEditor.cpp, src/NotepadNext/DockedEditor.h, src/NotepadNext/MacroListModel.cpp, src/NotepadNext/NotepadNext.pro, src/NotepadNext/dialogs/MainWindow.cpp, src/NotepadNext/dialogs/MainWindow.h, src/NotepadNext/docks/FileListDock.cpp, src/NotepadNext/docks/FileListDock.h, src/NotepadNext/docks/FileListDock.ui
=> Add File List Dock to show opened editors

src/NotepadNext/ComboBoxDelegate.cpp, src/NotepadNext/Converter.cpp, src/NotepadNext/Converter.h, src/NotepadNext/HtmlConverter.cpp, src/NotepadNext/HtmlConverter.h, src/NotepadNext/NotepadNext.pro, src/NotepadNext/RtfConverter.cpp, src/NotepadNext/RtfConverter.h, src/NotepadNext/dialogs/MainWindow.cpp, src/NotepadNext/dialogs/MainWindow.h, src/NotepadNext/dialogs/MainWindow.ui
=> Add copying/exporting as HTML and RTF

src/NotepadNext/NotepadNext.pro
=> Build universal (multi-architecture) binaries for MacOS

deploy/linux/NotepadNext.desktop
=> Fix for #305 - pass arguments to executable, from desktop file

i18n/NotepadNext.sv_SE.ts, i18n/NotepadNext.zh_CN.ts
just run `lupdate`
Translation updates in another pr.
=> Update i18n *.ts files

i18n/NotepadNext.zh_CN.ts
Maybe keep this pr open for 1 week and see if anyone wants to review it.
=> Update Chinese translation

deploy/macos/info.plist, deploy/macos/info.plist.in, src/NotepadNext/NotepadNext.pro
Qmake now builds a custom info.plist for MacOS. Closes #267
=> Add filename extension support on macOS

.github/workflows/build.yml
Not sure what changed but now it is missing the libxkbcommon-x11-0 library
=> Fix building of AppImage

.github/workflows/build.yml
=> Build with Qt6.5

i18n/NotepadNext_tr_TR.ts
Sorry, this take way longer than I anticipated.
I couldn't translate one thing because of how Turkish Grammer works, I left a comment at 158. Other than that, all translations were done with QT Linguist and are ready to merge!
=> Turkish Language Support

i18n/NotepadNext_tr_TR.ts
=> Update in tr_TR.ts

installer/installer.nsi
=> Add a checkbox to run the application when installation is finished

i18n/NotepadNext_zh_CN.ts
Signed-off-by: yangyangdaji <1504305527@qq.com>
=> Update Chinese (Simplified) Translation

i18n/NotepadNext_zh_CN.ts
`合并搜索结果` → `结合搜索结果`
Signed-off-by: yangyangdaji <1504305527@qq.com>
=> (i18n) Fix typo on Chinese Simplified (02cad87)

.github/workflows/build.yml, .github/workflows/lupdate.yml
Reverts dail8859/NotepadNext#470
https://github.com/jurplel/install-qt-action/issues/213
=> Revert "Bump jurplel/install-qt-action from 3 to 4"

src/NotepadNext/NotepadNextApplication.cpp, src/NotepadNext/NotepadNextApplication.h, src/NotepadNext/dialogs/MainWindow.cpp
Only supported on Windows currently
=> Update Window title to indication if running in admin mode

installer/installer.nsi
=> Add app to Window's "Open With" suggestions for text files

i18n/NotepadNext_pl_PL.ts
=> Polish translation

src/NotepadNext/dialogs/FindReplaceDialog.ui
=> Adapt the Find/Replace dialog UI for MAC

.github/workflows/build.yml
There's no way to exclude an object so get rid of "config"
=> Clean up github build action

i18n/NotepadNext_pt_PT.ts
* Minor corrections
* Translation update
=> Update Portuguese (Portugal) translation

src/NotepadNext/dialogs/MainWindow.cpp, src/NotepadNext/dialogs/MainWindow.ui, src/NotepadNext/widgets/EditorInfoStatusBar.cpp, src/NotepadNext/widgets/EditorInfoStatusBar.h
=> Add overtype toggling

src/NotepadNext/docks/SearchResultsDock.cpp, src/NotepadNext/docks/SearchResultsDock.h, src/NotepadNext/docks/SearchResultsDock.ui
Adds a button to the Search Results dock to copy the contents to the clipboard
=> [Feature request] Copy Search results #224

i18n/NotepadNext_uk_UA.ts
+ Fixed typo error
+ Fixed accelerators
+ Translated new strings
=> Updated Ukrainian translation

src/NotepadNext/ApplicationSettings.cpp, src/NotepadNext/ApplicationSettings.h, src/NotepadNext/EditorManager.cpp
=> Add additional word chars

src/NotepadNext/languages/c.lua
=> Fix keywords for C

src/NotepadNext/dialogs/MainWindow.cpp, src/NotepadNext/dialogs/MainWindow.h
=> Add loading of custom application styling

src/NotepadNext/docks/FileListDock.cpp, src/NotepadNext/docks/FileListDock.ui
=> Add option to sort file list by name

i18n/NotepadNext_zh_TW.ts
=> Update zh_TW Traditional Chinese locale

i18n/NotepadNext_pt_BR.ts, src/i18n.pri
- this PR includes a support for Brazilian Portuguese translation
=> Adds pt_BR translation

src/NotepadNext/decorators/BookMarkDecorator.cpp, src/NotepadNext/decorators/BookMarkDecorator.h, src/NotepadNext/dialogs/MainWindow.cpp, src/NotepadNext/dialogs/MainWindow.ui
=> Add more bookmark operations (cut/copy/delete)

src/NotepadNext/EditorManager.cpp, src/NotepadNext/NotepadNext.pro, src/NotepadNext/decorators/HTMLAutoCompleteDecorator.cpp, src/NotepadNext/decorators/HTMLAutoCompleteDecorator.h
=> Auto close HTML tags

src/NotepadNext/NotepadNextApplication.cpp, src/NotepadNext/languages/php.lua, src/NotepadNext/scripts/init.lua
=> Add HTML highlighting in PHP files

i18n/NotepadNext_pt_BR.ts
https://github.com/dail8859/NotepadNext/issues/717
=> Fix spelling mistake in pt_BR translation

i18n/NotepadNext_es_NI.ts
This new pull request fixes minor typos, a translation mistake in line 561, and a translation string in line 1523.
**Disclaimer:** this is actually my fifth pull request to this project, as I had problems with two previous pull request attempts (especially #722 and #723), apparently due to a merge conflict that forced me to close them, but I hope this one can be merged with success.
=> Update Spanish (Nicaragua) translation.

src/NotepadNext/dialogs/MainWindow.cpp, src/NotepadNext/dialogs/MainWindow.h
=> Allow customization of editor context menu

src/NotepadNext/DockedEditor.cpp, src/NotepadNext/DockedEditor.h
=> Update Qt Advanced Docking System

src/NotepadNext/dialogs/MainWindow.cpp, src/NotepadNext/dialogs/MainWindow.ui
=> Allow specifying multiple custom shortcuts for actions

i18n/NotepadNext_pt_BR.ts
Fix line 1212 (translation>Aumentar o recuo da linha</translation>) for (<translation>Aumentar o recuo da linha</translation>)
=> Fix line 1212 (translation>Aumentar o recuo da linha</translation>)

src/NotepadNext/ActionUtils.h, src/NotepadNext/NotepadNext.pro, src/NotepadNext/NotepadNextApplication.cpp, src/NotepadNext/decorators/MarkerAppDecorator.cpp, src/NotepadNext/decorators/MarkerAppDecorator.h, src/NotepadNext/dialogs/MainWindow.cpp, src/NotepadNext/dialogs/MainWindow.ui
=> Mark token occurrences with specific colors

updates.json
Closes https://github.com/dail8859/NotepadNext/issues/790.
=> Update updates.json for to v0.12
